### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rustc-guide#293] opened 2019-03-29 23:37 UTC
@Mark-Simulacrum It appears the following is returning error 500: https://buildbot2.rust-lang.org/homu/

Do you know what the problem could be?

**Comment by pietroalbini** [comment] 2019-04-01 22:12
This happened after rustlings homu was deployed, and afaik it was never fixed. Maybe you can take a look at the server?

**Comment by mark-i-m** [comment] 2019-04-01 23:01
What do you mean by “take a look at yhr server”?

**Comment by pietroalbini** [comment] 2019-04-02 08:49
The link *should* be alive, I asked Mark to check if there is something wrong on central station.

**Comment by pietroalbini** [comment] 2019-04-02 17:12
Duplicate of https://github.com/rust-lang/rust/issues/59475

**Comment by mark-i-m** [comment] 2019-04-02 17:28
I would like to leave this open so I don't forget to (at least temporarily) remove the link from the guide.

**Comment by Mark-Simulacrum** [comment] 2019-04-02 18:35
Well, https://buildbot2.rust-lang.org/homu/ is fixed now it seems after redeploying.

**Closed** 2019-04-02 18:46 UTC
